  - name: fart
    address: 127.0.0.1:25575
    password: minecraft
  - name: Survival
    address: 127.0.0.1:25576
    password: 6or7
  - name: UseGateasyourProxy!
    address: 127.0.0.1:25577
    password: mewhen