servers:
  - name: fart
    address: 127.0.0.1:25575
    password: minecraft
    container: minecraft_server_1
  - name: Survival
    address: 127.0.0.1:25576
    password: 6or7
    container: minecraft_survival
  - name: UseGateasyourProxy!
    address: 127.0.0.1:25577
    password: mewhen
    container: minecraft_proxy